// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantHub.Web.Infrastructure;

#nullable disable

namespace PlantHub.Web.Migrations
{
    [DbContext(typeof(PlantHubDbContext))]
    [Migration("20251211210307_AddWateringEventTable")]
    partial class AddWateringEventTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PlantHub.Web.Domain.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatinName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MoistureHighPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("MoistureLowPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PotVolumeMl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SensorEntityId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WateringGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("WateringGroupId");

                    b.ToTable("Plants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Plant_MoistureHigh_0_100", "(MoistureHighPercent IS NULL) OR (MoistureHighPercent BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("CK_Plant_MoistureLow_0_100", "(MoistureLowPercent IS NULL) OR (MoistureLowPercent BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("CK_Plant_PotVolume_Positive", "(PotVolumeMl IS NULL) OR (PotVolumeMl > 0)");

                            t.HasCheckConstraint("CK_Plant_ScheduleGroup", "(Mode <> 0) OR (WateringGroupId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PlantHub.Web.Domain.WateringEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("WateringEvents", (string)null);
                });

            modelBuilder.Entity("PlantHub.Web.Domain.WateringGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalDaysSummer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalDaysWinter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxDaysBetween")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinDaysBetween")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SummerEndMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(9);

                    b.Property<int>("SummerStartMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WateringGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_WG_Interval_Summer", "IntervalDaysSummer >= 1");

                            t.HasCheckConstraint("CK_WG_Interval_Winter", "IntervalDaysWinter >= 1");

                            t.HasCheckConstraint("CK_WG_Max_Positive", "(MaxDaysBetween IS NULL) OR (MaxDaysBetween >= 1)");

                            t.HasCheckConstraint("CK_WG_MinLEMax", "(MinDaysBetween IS NULL) OR (MaxDaysBetween IS NULL) OR (MinDaysBetween <= MaxDaysBetween)");

                            t.HasCheckConstraint("CK_WG_Min_Positive", "(MinDaysBetween IS NULL) OR (MinDaysBetween >= 1)");

                            t.HasCheckConstraint("CK_WG_Month_End", "SummerEndMonth BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_WG_Month_Start", "SummerStartMonth BETWEEN 1 AND 12");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Very drought-tolerant plants. Let soil dry completely. Typical: aloe, cacti, succulents.",
                            IntervalDaysSummer = 14,
                            IntervalDaysWinter = 21,
                            MaxDaysBetween = 30,
                            MinDaysBetween = 14,
                            Name = "Succulents & Cacti",
                            SummerEndMonth = 9,
                            SummerStartMonth = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Green foliage that prefers to dry slightly between waterings. Typical: monstera, pothos, umbrella plant.",
                            IntervalDaysSummer = 7,
                            IntervalDaysWinter = 10,
                            MaxDaysBetween = 14,
                            MinDaysBetween = 7,
                            Name = "Drought-Tolerant Green Foliage",
                            SummerEndMonth = 9,
                            SummerStartMonth = 5
                        },
                        new
                        {
                            Id = 3,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plants that like lightly and evenly moist soil. Typical: coleus (palettblad), indoor pelargonium.",
                            IntervalDaysSummer = 4,
                            IntervalDaysWinter = 6,
                            MaxDaysBetween = 7,
                            MinDaysBetween = 3,
                            Name = "Thirsty Foliage & Flowering",
                            SummerEndMonth = 9,
                            SummerStartMonth = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Citrus and olive in larger pots. Let dry lightly between waterings, adjust more between seasons.",
                            IntervalDaysSummer = 5,
                            IntervalDaysWinter = 14,
                            MaxDaysBetween = 21,
                            MinDaysBetween = 3,
                            Name = "Mediterranean Trees",
                            SummerEndMonth = 9,
                            SummerStartMonth = 5
                        });
                });

            modelBuilder.Entity("PlantHub.Web.Domain.Plant", b =>
                {
                    b.HasOne("PlantHub.Web.Domain.WateringGroup", "WateringGroup")
                        .WithMany("Plants")
                        .HasForeignKey("WateringGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WateringGroup");
                });

            modelBuilder.Entity("PlantHub.Web.Domain.WateringEvent", b =>
                {
                    b.HasOne("PlantHub.Web.Domain.Plant", "Plant")
                        .WithMany("WateringEvents")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantHub.Web.Domain.Plant", b =>
                {
                    b.Navigation("WateringEvents");
                });

            modelBuilder.Entity("PlantHub.Web.Domain.WateringGroup", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
